HHOURLY, HOURLY output options added
CMCC-Foundation/CAM pull request #4
Opened 2023-01-30 09:46 UTC by giovanniconti83

Added output options for cam.i file in order to use FGAT in spreads.

2023-01-30 21:46 UTC, gold2718 requested changes
I'm not sure I understand how this works. Perhaps answers to my questions will help.

2023-01-30 21:46 UTC, gold2718 commented on bld/namelist_files/namelist_definition.xml
> +       group="cam_history_nl" valid_values="NONE,6-HOURLY,DAILY,MONTHLY,YEARLY,CAMIOP,ENDOFRUN,HHOURLY,HOURLY" >
Ick! I think we have too many special cases and it is too much work introducing a new one.
On the other hand, a better solution is a big job that I think will be done as part of the new CAM history implementation.

2023-01-30 21:46 UTC, gold2718 commented on src/control/cam_history.F90
> +  !GC
In ESCOMP/CAM, we don't usually include initials in the code (over time, no one knows who this is). I suggest adding a full name / GitHub ID to the PR description so that it ends up on the log.

2023-01-30 21:46 UTC, gold2718 commented on src/physics/cam/cam_diagnostics.F90
> +
Is this new line needed?

2023-01-30 21:46 UTC, gold2718 commented on src/physics/cam/cam_diagnostics.F90
> +
Is this new line needed?

2023-01-30 21:46 UTC, gold2718 commented on src/physics/cam/cam_diagnostics.F90
> +      call add_default ('U10     ', 1, ' ')
Why are these moved?

2023-01-30 21:46 UTC, gold2718 commented on src/physics/cam/cam_diagnostics.F90
> +      call add_default ('OCNFRAC ', 0, 'I')
Why aren't these `IC` variables?
```suggestion
      !GC add these variables to the i.c. for spreads. DA radiances, RTTOV needs
      !these.
      call add_default ('TS&IC   ', 0, 'I')
      call add_default ('TREFHT&IC', 0, 'I')
      call add_default ('LANDFRAC&IC', 0, 'I')
      call add_default ('OCNFRAC&IC', 0, 'I')
```

2023-01-30 21:46 UTC, gold2718 commented on src/physics/cam/cam_diagnostics.F90
> +        call outfld('TS&IC   ',conv_var_2d, pcols,lchnk)
Is there an `addfld` that matches this `outfld`? I have the same question about the four other `outfld` calls below.

2023-01-31 08:15 UTC, giovanniconti83 commented on bld/namelist_files/namelist_definition.xml
> +       group="cam_history_nl" valid_values="NONE,6-HOURLY,DAILY,MONTHLY,YEARLY,CAMIOP,ENDOFRUN,HHOURLY,HOURLY" >
I understand your point, however to be able to use the radiances forward operator in a FGAT EnKF framework we need this kind of frequency output. As you suggested, better solutions would require a much bigger effort.

2023-01-31 08:19 UTC, giovanniconti83 commented on src/control/cam_history.F90
> +  !GC
Thanks for the suggestion. This was my way to track the changes inside the code and move to them quickly with a find command inside vim. I'll remove them all.

2023-01-31 08:21 UTC, giovanniconti83 commented on src/physics/cam/cam_diagnostics.F90
> +
Actually these lines are not mine, more likely when I deleted one my comment I moved these lines and they appear now in the changes done, but I did not touch those two lines.

2023-01-31 08:23 UTC, giovanniconti83 commented on src/physics/cam/cam_diagnostics.F90
> +
As above, these three lines have not been changed by me, more likely they have been shifted up during some cleaning of my comments.

2023-01-31 08:25 UTC, giovanniconti83 commented on src/physics/cam/cam_diagnostics.F90
> +      call add_default ('U10     ', 1, ' ')
We set some comments when we tried to understand how the writing of the field was working and at the end we deleted them . . . generating some unuseful line shift.

2023-01-31 09:01 UTC, giovanniconti83 commented on src/physics/cam/cam_diagnostics.F90
> +      call add_default ('OCNFRAC ', 0, 'I')
I did a test with the changes you suggest here, but I get this error:

ERROR: ADD_DEFAULT: field = "TS&IC" not found
 ERROR: ADD_DEFAULT: field = "TS&IC" not found
Image              PC                Routine            Line        Source
cesm.exe           0000000003022906  Unknown               Unknown  Unknown
cesm.exe           0000000002AFA964  shr_abort_mod_mp_         114  shr_abort_mod.F90
cesm.exe           00000000005D6E8F  cam_history_mp_ad        3816  cam_history.F90
cesm.exe           00000000011F0F21  cam_diagnostics_m         697  cam_diagnostics.F90
cesm.exe           00000000007E5CCF  physpkg_mp_phys_i         793  physpkg.F90
cesm.exe           00000000005A3A96  cam_comp_mp_cam_i         199  cam_comp.F90
cesm.exe           0000000000590144  atm_comp_nuopc_mp         613  atm_comp_nuopc.F90

2023-01-31 09:02 UTC, giovanniconti83 commented on src/physics/cam/cam_diagnostics.F90
> +        call outfld('TS&IC   ',conv_var_2d, pcols,lchnk)
I think this is necessary to write correctly the fields. Without these we got some errors.

2023-01-31 12:09 UTC, gold2718 commented on src/physics/cam/cam_diagnostics.F90
> +        call outfld('TS&IC   ',conv_var_2d, pcols,lchnk)
My point is that you are missing an `addfld` call for these fields.

2023-01-31 12:09 UTC, gold2718 commented on src/physics/cam/cam_diagnostics.F90
> +      call add_default ('OCNFRAC ', 0, 'I')
This is expected, you do not have an `addfld` call for these fields (see my comment below).

2023-02-01 13:07 UTC, gold2718 approved these changes
Much cleaner!

2023-02-09 09:52 UTC, merged

2023-02-09 09:53 UTC, daniele-peano reviewed
Merged